### PR TITLE
Add Config-value documentation and a test. Remove an inadvertant printf.

### PR DESCRIPTION
**Pull request by smoser**
Follow on to #78 to:
   - Remove debug Printf.
   - Add test for config substitutions.
   - Add some helpers for tests (umount_under, stderr, tmpd, cmp_files)
   - Add some doc for config file substitutions.

### CODE REVIEW

**Comment by tych0** [comment]
Seems like the test is busted?

**Comment by smoser** [comment]
Test runs for me locally... Give it a try?

**Comment by tych0** [comment]
Too bad we don't run CI on your machine :)

I think it's because you're using a non-broken lxc-common package that has lxc.init.static. The ones in ubuntu are broken, and it's not statically linked, so it fails to start. When I switch to using centos:latest instead of busybox:latest, it passes: https://travis-ci.org/tych0/stacker/builds/658867521

**Comment by smoser** [comment]
@tych0 
Take another look.  Moved back to centos :cry: . And re-worked some cleanup.

**Comment by tych0** [comment]
Cool, thanks!

**Pull request merged**
