### PR TITLE
Add docker-daemon transport to the supported transports

### PR DESCRIPTION
**Pull request by rnataraja**
Raising this PR for comments, I am currently testing this change.

### CODE REVIEW

**Comment by rnataraja** [comment]
Tested with stacker library used by our internal tool. The change works.

**Comment by rnataraja** [comment]
@tych0  Pls take a look at this PR.

**Comment by tych0** [comment]
Looks good to me, assuming CI passes. Any reason you labeled this "Draft"?

**Comment by rnataraja** [comment]
> Looks good to me, assuming CI passes. Any reason you labeled this "Draft"?

No I did not mark this as a Draft. I had initially created with Title "Draft:", but then after testing changes, I removed it that word from the Title of the PR.

**Comment by tych0** [comment]
> I removed it that word from the Title of the PR.

I still see it there? But ok, sounds like it's not a draft in any case.

**Pull request merged**
