### PR TITLE
fix unprivileged builds using tar and scratch imports

### LINKED ISSUE #30: unpriv unpack sometimes fails
I'm getting:

```
error: umoci unpack failed: create runtime bundle: unpack rootfs: chown rootfs: lchown /btrfs/shallyn/atomix/installer/roots/.working/rootfs: operation not permitted
```

Some simpler stacker builds do work, but "from: type: tar" does not.

To reproduce:

```
cat > stacker.yaml << EOF
tar:
    from:
        type: tar
        url: my.tar.gz
EOF
touch x y z
tar zcf my.tar.gz x y z
stacker build
```

### PR DESCRIPTION
**Pull request by hallyn**
Umoci actually does try to lchown the newly initialized, empty,
oci layout when you unpack it.  So do so in a new userns.  This
requires a new 'stacker umoci init' subcommand since $golang.

Closes #30

Signed-off-by: Serge Hallyn <shallyn@cisco.com>

### CODE REVIEW

**Comment by tych0** [comment]
Looks like you need a go fmt? lgtm otherwise.

**Comment by hallyn** [comment]
fascist bastards

**Comment by hallyn** [comment]
Why is 'go fmt' fetching all sorts of requirements?  just format my code!

**Comment by tych0** [comment]
Go modules maybe? :-(

**Pull request merged**
